// Generated by gencpp from file pkg_testservice/img_srv.msg
// DO NOT EDIT!


#ifndef PKG_TESTSERVICE_MESSAGE_IMG_SRV_H
#define PKG_TESTSERVICE_MESSAGE_IMG_SRV_H

#include <ros/service_traits.h>


#include <pkg_testservice/img_srvRequest.h>
#include <pkg_testservice/img_srvResponse.h>


namespace pkg_testservice
{

struct img_srv
{

typedef img_srvRequest Request;
typedef img_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct img_srv
} // namespace pkg_testservice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_testservice::img_srv > {
  static const char* value()
  {
    return "344046330d50eb39af6c3963f87cb9cd";
  }

  static const char* value(const ::pkg_testservice::img_srv&) { return value(); }
};

template<>
struct DataType< ::pkg_testservice::img_srv > {
  static const char* value()
  {
    return "pkg_testservice/img_srv";
  }

  static const char* value(const ::pkg_testservice::img_srv&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_testservice::img_srvRequest> should match
// service_traits::MD5Sum< ::pkg_testservice::img_srv >
template<>
struct MD5Sum< ::pkg_testservice::img_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_testservice::img_srv >::value();
  }
  static const char* value(const ::pkg_testservice::img_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_testservice::img_srvRequest> should match
// service_traits::DataType< ::pkg_testservice::img_srv >
template<>
struct DataType< ::pkg_testservice::img_srvRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_testservice::img_srv >::value();
  }
  static const char* value(const ::pkg_testservice::img_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_testservice::img_srvResponse> should match
// service_traits::MD5Sum< ::pkg_testservice::img_srv >
template<>
struct MD5Sum< ::pkg_testservice::img_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_testservice::img_srv >::value();
  }
  static const char* value(const ::pkg_testservice::img_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_testservice::img_srvResponse> should match
// service_traits::DataType< ::pkg_testservice::img_srv >
template<>
struct DataType< ::pkg_testservice::img_srvResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_testservice::img_srv >::value();
  }
  static const char* value(const ::pkg_testservice::img_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_TESTSERVICE_MESSAGE_IMG_SRV_H
