// Generated by gencpp from file pkg_cv/img_srv.msg
// DO NOT EDIT!


#ifndef PKG_CV_MESSAGE_IMG_SRV_H
#define PKG_CV_MESSAGE_IMG_SRV_H

#include <ros/service_traits.h>


#include <pkg_cv/img_srvRequest.h>
#include <pkg_cv/img_srvResponse.h>


namespace pkg_cv
{

struct img_srv
{

typedef img_srvRequest Request;
typedef img_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct img_srv
} // namespace pkg_cv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_cv::img_srv > {
  static const char* value()
  {
    return "01d253bb9c4556a79a141bb7d6d1c6cf";
  }

  static const char* value(const ::pkg_cv::img_srv&) { return value(); }
};

template<>
struct DataType< ::pkg_cv::img_srv > {
  static const char* value()
  {
    return "pkg_cv/img_srv";
  }

  static const char* value(const ::pkg_cv::img_srv&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_cv::img_srvRequest> should match
// service_traits::MD5Sum< ::pkg_cv::img_srv >
template<>
struct MD5Sum< ::pkg_cv::img_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_cv::img_srv >::value();
  }
  static const char* value(const ::pkg_cv::img_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_cv::img_srvRequest> should match
// service_traits::DataType< ::pkg_cv::img_srv >
template<>
struct DataType< ::pkg_cv::img_srvRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_cv::img_srv >::value();
  }
  static const char* value(const ::pkg_cv::img_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_cv::img_srvResponse> should match
// service_traits::MD5Sum< ::pkg_cv::img_srv >
template<>
struct MD5Sum< ::pkg_cv::img_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_cv::img_srv >::value();
  }
  static const char* value(const ::pkg_cv::img_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_cv::img_srvResponse> should match
// service_traits::DataType< ::pkg_cv::img_srv >
template<>
struct DataType< ::pkg_cv::img_srvResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_cv::img_srv >::value();
  }
  static const char* value(const ::pkg_cv::img_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_CV_MESSAGE_IMG_SRV_H
