// Generated by gencpp from file pkg_cv/img_srvResponse.msg
// DO NOT EDIT!


#ifndef PKG_CV_MESSAGE_IMG_SRVRESPONSE_H
#define PKG_CV_MESSAGE_IMG_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_cv
{
template <class ContainerAllocator>
struct img_srvResponse_
{
  typedef img_srvResponse_<ContainerAllocator> Type;

  img_srvResponse_()
    : response(0)  {
    }
  img_srvResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef int64_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::pkg_cv::img_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_cv::img_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct img_srvResponse_

typedef ::pkg_cv::img_srvResponse_<std::allocator<void> > img_srvResponse;

typedef boost::shared_ptr< ::pkg_cv::img_srvResponse > img_srvResponsePtr;
typedef boost::shared_ptr< ::pkg_cv::img_srvResponse const> img_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_cv::img_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_cv::img_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_cv::img_srvResponse_<ContainerAllocator1> & lhs, const ::pkg_cv::img_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_cv::img_srvResponse_<ContainerAllocator1> & lhs, const ::pkg_cv::img_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_cv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_cv::img_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_cv::img_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_cv::img_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bf37bc717f68787645077428bea3751";
  }

  static const char* value(const ::pkg_cv::img_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bf37bc717f68787ULL;
  static const uint64_t static_value2 = 0x645077428bea3751ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_cv/img_srvResponse";
  }

  static const char* value(const ::pkg_cv::img_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 response\n"
"\n"
;
  }

  static const char* value(const ::pkg_cv::img_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct img_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_cv::img_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_cv::img_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int64_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_CV_MESSAGE_IMG_SRVRESPONSE_H
