// Generated by gencpp from file subt_msgs/artifact.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_ARTIFACT_H
#define SUBT_MSGS_MESSAGE_ARTIFACT_H

#include <ros/service_traits.h>


#include <subt_msgs/artifactRequest.h>
#include <subt_msgs/artifactResponse.h>


namespace subt_msgs
{

struct artifact
{

typedef artifactRequest Request;
typedef artifactResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct artifact
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::artifact > {
  static const char* value()
  {
    return "69bcd85d6d5bff1b077f8d902e21fd09";
  }

  static const char* value(const ::subt_msgs::artifact&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::artifact > {
  static const char* value()
  {
    return "subt_msgs/artifact";
  }

  static const char* value(const ::subt_msgs::artifact&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::artifactRequest> should match
// service_traits::MD5Sum< ::subt_msgs::artifact >
template<>
struct MD5Sum< ::subt_msgs::artifactRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::artifact >::value();
  }
  static const char* value(const ::subt_msgs::artifactRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::artifactRequest> should match
// service_traits::DataType< ::subt_msgs::artifact >
template<>
struct DataType< ::subt_msgs::artifactRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::artifact >::value();
  }
  static const char* value(const ::subt_msgs::artifactRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::artifactResponse> should match
// service_traits::MD5Sum< ::subt_msgs::artifact >
template<>
struct MD5Sum< ::subt_msgs::artifactResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::artifact >::value();
  }
  static const char* value(const ::subt_msgs::artifactResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::artifactResponse> should match
// service_traits::DataType< ::subt_msgs::artifact >
template<>
struct DataType< ::subt_msgs::artifactResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::artifact >::value();
  }
  static const char* value(const ::subt_msgs::artifactResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_ARTIFACT_H
