// Generated by gencpp from file subt_msgs/ArtifactPoseArray.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_ARTIFACTPOSEARRAY_H
#define SUBT_MSGS_MESSAGE_ARTIFACTPOSEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <subt_msgs/ArtifactPose.h>

namespace subt_msgs
{
template <class ContainerAllocator>
struct ArtifactPoseArray_
{
  typedef ArtifactPoseArray_<ContainerAllocator> Type;

  ArtifactPoseArray_()
    : header()
    , camera()
    , count(0)
    , pose_array()  {
    }
  ArtifactPoseArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , camera(_alloc)
    , count(0)
    , pose_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _camera_type;
  _camera_type camera;

   typedef int32_t _count_type;
  _count_type count;

   typedef std::vector< ::subt_msgs::ArtifactPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::subt_msgs::ArtifactPose_<ContainerAllocator> >::other >  _pose_array_type;
  _pose_array_type pose_array;





  typedef boost::shared_ptr< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> const> ConstPtr;

}; // struct ArtifactPoseArray_

typedef ::subt_msgs::ArtifactPoseArray_<std::allocator<void> > ArtifactPoseArray;

typedef boost::shared_ptr< ::subt_msgs::ArtifactPoseArray > ArtifactPoseArrayPtr;
typedef boost::shared_ptr< ::subt_msgs::ArtifactPoseArray const> ArtifactPoseArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator1> & lhs, const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.camera == rhs.camera &&
    lhs.count == rhs.count &&
    lhs.pose_array == rhs.pose_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator1> & lhs, const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1241fdc583a1d4a260d1fbeb9ee080f0";
  }

  static const char* value(const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1241fdc583a1d4a2ULL;
  static const uint64_t static_value2 = 0x60d1fbeb9ee080f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/ArtifactPoseArray";
  }

  static const char* value(const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string camera\n"
"int32 count\n"
"ArtifactPose[] pose_array\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: subt_msgs/ArtifactPose\n"
"string Class\n"
"#string status				# O for non_return , X for return \n"
"int32 appear_count\n"
"float64 probability\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.camera);
      stream.next(m.count);
      stream.next(m.pose_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArtifactPoseArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::ArtifactPoseArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "camera: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "pose_array[]" << std::endl;
    for (size_t i = 0; i < v.pose_array.size(); ++i)
    {
      s << indent << "  pose_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::subt_msgs::ArtifactPose_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_ARTIFACTPOSEARRAY_H
