// Generated by gencpp from file subt_msgs/GloraPack.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_GLORAPACK_H
#define SUBT_MSGS_MESSAGE_GLORAPACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace subt_msgs
{
template <class ContainerAllocator>
struct GloraPack_
{
  typedef GloraPack_<ContainerAllocator> Type;

  GloraPack_()
    : header()
    , packet()
    , time_elapse(0.0)
    , success(false)  {
    }
  GloraPack_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packet(_alloc)
    , time_elapse(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _packet_type;
  _packet_type packet;

   typedef float _time_elapse_type;
  _time_elapse_type time_elapse;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::subt_msgs::GloraPack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::GloraPack_<ContainerAllocator> const> ConstPtr;

}; // struct GloraPack_

typedef ::subt_msgs::GloraPack_<std::allocator<void> > GloraPack;

typedef boost::shared_ptr< ::subt_msgs::GloraPack > GloraPackPtr;
typedef boost::shared_ptr< ::subt_msgs::GloraPack const> GloraPackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::GloraPack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::GloraPack_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::GloraPack_<ContainerAllocator1> & lhs, const ::subt_msgs::GloraPack_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.packet == rhs.packet &&
    lhs.time_elapse == rhs.time_elapse &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::GloraPack_<ContainerAllocator1> & lhs, const ::subt_msgs::GloraPack_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::GloraPack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::GloraPack_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::GloraPack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::GloraPack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::GloraPack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::GloraPack_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::GloraPack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "793b4359128b7f4b7385d49cb96eaaec";
  }

  static const char* value(const ::subt_msgs::GloraPack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x793b4359128b7f4bULL;
  static const uint64_t static_value2 = 0x7385d49cb96eaaecULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::GloraPack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/GloraPack";
  }

  static const char* value(const ::subt_msgs::GloraPack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::GloraPack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string packet\n"
"float32 time_elapse \n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::subt_msgs::GloraPack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::GloraPack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packet);
      stream.next(m.time_elapse);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GloraPack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::GloraPack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::GloraPack_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "packet: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.packet);
    s << indent << "time_elapse: ";
    Printer<float>::stream(s, indent + "  ", v.time_elapse);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_GLORAPACK_H
