// Generated by gencpp from file subt_msgs/mask_center.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_MASK_CENTER_H
#define SUBT_MSGS_MESSAGE_MASK_CENTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_msgs
{
template <class ContainerAllocator>
struct mask_center_
{
  typedef mask_center_<ContainerAllocator> Type;

  mask_center_()
    : Class()
    , x(0)
    , y(0)
    , z(0)  {
    }
  mask_center_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::subt_msgs::mask_center_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::mask_center_<ContainerAllocator> const> ConstPtr;

}; // struct mask_center_

typedef ::subt_msgs::mask_center_<std::allocator<void> > mask_center;

typedef boost::shared_ptr< ::subt_msgs::mask_center > mask_centerPtr;
typedef boost::shared_ptr< ::subt_msgs::mask_center const> mask_centerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::mask_center_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::mask_center_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::mask_center_<ContainerAllocator1> & lhs, const ::subt_msgs::mask_center_<ContainerAllocator2> & rhs)
{
  return lhs.Class == rhs.Class &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::mask_center_<ContainerAllocator1> & lhs, const ::subt_msgs::mask_center_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::mask_center_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::mask_center_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::mask_center_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::mask_center_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::mask_center_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::mask_center_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::mask_center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6475a486473154bd09397e55a585b9d4";
  }

  static const char* value(const ::subt_msgs::mask_center_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6475a486473154bdULL;
  static const uint64_t static_value2 = 0x09397e55a585b9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::mask_center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/mask_center";
  }

  static const char* value(const ::subt_msgs::mask_center_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::mask_center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n"
"int64 x\n"
"int64 y\n"
"int64 z\n"
;
  }

  static const char* value(const ::subt_msgs::mask_center_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::mask_center_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mask_center_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::mask_center_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::mask_center_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_MASK_CENTER_H
