// Generated by gencpp from file subt_msgs/node_stat.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_NODE_STAT_H
#define SUBT_MSGS_MESSAGE_NODE_STAT_H

#include <ros/service_traits.h>


#include <subt_msgs/node_statRequest.h>
#include <subt_msgs/node_statResponse.h>


namespace subt_msgs
{

struct node_stat
{

typedef node_statRequest Request;
typedef node_statResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_stat
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::node_stat > {
  static const char* value()
  {
    return "54387671ddc71365ab725d0391f330f3";
  }

  static const char* value(const ::subt_msgs::node_stat&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::node_stat > {
  static const char* value()
  {
    return "subt_msgs/node_stat";
  }

  static const char* value(const ::subt_msgs::node_stat&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::node_statRequest> should match
// service_traits::MD5Sum< ::subt_msgs::node_stat >
template<>
struct MD5Sum< ::subt_msgs::node_statRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::node_stat >::value();
  }
  static const char* value(const ::subt_msgs::node_statRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::node_statRequest> should match
// service_traits::DataType< ::subt_msgs::node_stat >
template<>
struct DataType< ::subt_msgs::node_statRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::node_stat >::value();
  }
  static const char* value(const ::subt_msgs::node_statRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::node_statResponse> should match
// service_traits::MD5Sum< ::subt_msgs::node_stat >
template<>
struct MD5Sum< ::subt_msgs::node_statResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::node_stat >::value();
  }
  static const char* value(const ::subt_msgs::node_statResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::node_statResponse> should match
// service_traits::DataType< ::subt_msgs::node_stat >
template<>
struct DataType< ::subt_msgs::node_statResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::node_stat >::value();
  }
  static const char* value(const ::subt_msgs::node_statResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_NODE_STAT_H
