// Generated by gencpp from file subt_msgs/pause.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_PAUSE_H
#define SUBT_MSGS_MESSAGE_PAUSE_H

#include <ros/service_traits.h>


#include <subt_msgs/pauseRequest.h>
#include <subt_msgs/pauseResponse.h>


namespace subt_msgs
{

struct pause
{

typedef pauseRequest Request;
typedef pauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pause
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::pause > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::subt_msgs::pause&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::pause > {
  static const char* value()
  {
    return "subt_msgs/pause";
  }

  static const char* value(const ::subt_msgs::pause&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::pauseRequest> should match
// service_traits::MD5Sum< ::subt_msgs::pause >
template<>
struct MD5Sum< ::subt_msgs::pauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::pause >::value();
  }
  static const char* value(const ::subt_msgs::pauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::pauseRequest> should match
// service_traits::DataType< ::subt_msgs::pause >
template<>
struct DataType< ::subt_msgs::pauseRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::pause >::value();
  }
  static const char* value(const ::subt_msgs::pauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::pauseResponse> should match
// service_traits::MD5Sum< ::subt_msgs::pause >
template<>
struct MD5Sum< ::subt_msgs::pauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::pause >::value();
  }
  static const char* value(const ::subt_msgs::pauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::pauseResponse> should match
// service_traits::DataType< ::subt_msgs::pause >
template<>
struct DataType< ::subt_msgs::pauseResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::pause >::value();
  }
  static const char* value(const ::subt_msgs::pauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_PAUSE_H
