// Generated by gencpp from file subt_msgs/pose.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_POSE_H
#define SUBT_MSGS_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <subt_msgs/poseRequest.h>
#include <subt_msgs/poseResponse.h>


namespace subt_msgs
{

struct pose
{

typedef poseRequest Request;
typedef poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::pose > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::subt_msgs::pose&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::pose > {
  static const char* value()
  {
    return "subt_msgs/pose";
  }

  static const char* value(const ::subt_msgs::pose&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::poseRequest> should match
// service_traits::MD5Sum< ::subt_msgs::pose >
template<>
struct MD5Sum< ::subt_msgs::poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::pose >::value();
  }
  static const char* value(const ::subt_msgs::poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::poseRequest> should match
// service_traits::DataType< ::subt_msgs::pose >
template<>
struct DataType< ::subt_msgs::poseRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::pose >::value();
  }
  static const char* value(const ::subt_msgs::poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::poseResponse> should match
// service_traits::MD5Sum< ::subt_msgs::pose >
template<>
struct MD5Sum< ::subt_msgs::poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::pose >::value();
  }
  static const char* value(const ::subt_msgs::poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::poseResponse> should match
// service_traits::DataType< ::subt_msgs::pose >
template<>
struct DataType< ::subt_msgs::poseResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::pose >::value();
  }
  static const char* value(const ::subt_msgs::poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_POSE_H
