// Generated by gencpp from file subt_msgs/status.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_STATUS_H
#define SUBT_MSGS_MESSAGE_STATUS_H

#include <ros/service_traits.h>


#include <subt_msgs/statusRequest.h>
#include <subt_msgs/statusResponse.h>


namespace subt_msgs
{

struct status
{

typedef statusRequest Request;
typedef statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct status
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::status > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::subt_msgs::status&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::status > {
  static const char* value()
  {
    return "subt_msgs/status";
  }

  static const char* value(const ::subt_msgs::status&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::statusRequest> should match
// service_traits::MD5Sum< ::subt_msgs::status >
template<>
struct MD5Sum< ::subt_msgs::statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::status >::value();
  }
  static const char* value(const ::subt_msgs::statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::statusRequest> should match
// service_traits::DataType< ::subt_msgs::status >
template<>
struct DataType< ::subt_msgs::statusRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::status >::value();
  }
  static const char* value(const ::subt_msgs::statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::statusResponse> should match
// service_traits::MD5Sum< ::subt_msgs::status >
template<>
struct MD5Sum< ::subt_msgs::statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::status >::value();
  }
  static const char* value(const ::subt_msgs::statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::statusResponse> should match
// service_traits::DataType< ::subt_msgs::status >
template<>
struct DataType< ::subt_msgs::statusResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::status >::value();
  }
  static const char* value(const ::subt_msgs::statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_STATUS_H
