// Generated by gencpp from file subt_msgs/stop.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_STOP_H
#define SUBT_MSGS_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <subt_msgs/stopRequest.h>
#include <subt_msgs/stopResponse.h>


namespace subt_msgs
{

struct stop
{

typedef stopRequest Request;
typedef stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::stop > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::subt_msgs::stop&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::stop > {
  static const char* value()
  {
    return "subt_msgs/stop";
  }

  static const char* value(const ::subt_msgs::stop&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::stopRequest> should match
// service_traits::MD5Sum< ::subt_msgs::stop >
template<>
struct MD5Sum< ::subt_msgs::stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::stop >::value();
  }
  static const char* value(const ::subt_msgs::stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::stopRequest> should match
// service_traits::DataType< ::subt_msgs::stop >
template<>
struct DataType< ::subt_msgs::stopRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::stop >::value();
  }
  static const char* value(const ::subt_msgs::stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::stopResponse> should match
// service_traits::MD5Sum< ::subt_msgs::stop >
template<>
struct MD5Sum< ::subt_msgs::stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::stop >::value();
  }
  static const char* value(const ::subt_msgs::stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::stopResponse> should match
// service_traits::DataType< ::subt_msgs::stop >
template<>
struct DataType< ::subt_msgs::stopResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::stop >::value();
  }
  static const char* value(const ::subt_msgs::stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_STOP_H
