// Generated by gencpp from file subt_msgs/ultra_infoResponse.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_ULTRA_INFORESPONSE_H
#define SUBT_MSGS_MESSAGE_ULTRA_INFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_msgs
{
template <class ContainerAllocator>
struct ultra_infoResponse_
{
  typedef ultra_infoResponse_<ContainerAllocator> Type;

  ultra_infoResponse_()
    : status(false)
    , height(0.0)  {
    }
  ultra_infoResponse_(const ContainerAllocator& _alloc)
    : status(false)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ultra_infoResponse_

typedef ::subt_msgs::ultra_infoResponse_<std::allocator<void> > ultra_infoResponse;

typedef boost::shared_ptr< ::subt_msgs::ultra_infoResponse > ultra_infoResponsePtr;
typedef boost::shared_ptr< ::subt_msgs::ultra_infoResponse const> ultra_infoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::ultra_infoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::ultra_infoResponse_<ContainerAllocator1> & lhs, const ::subt_msgs::ultra_infoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::ultra_infoResponse_<ContainerAllocator1> & lhs, const ::subt_msgs::ultra_infoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "839104ea8fff48a8d67dee52c3b6127a";
  }

  static const char* value(const ::subt_msgs::ultra_infoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x839104ea8fff48a8ULL;
  static const uint64_t static_value2 = 0xd67dee52c3b6127aULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/ultra_infoResponse";
  }

  static const char* value(const ::subt_msgs::ultra_infoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response data\n"
"bool status		# True for normal, False for danger\n"
"float32 height\n"
"# string result # for mission result\n"
;
  }

  static const char* value(const ::subt_msgs::ultra_infoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultra_infoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::ultra_infoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::ultra_infoResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_ULTRA_INFORESPONSE_H
