// Generated by gencpp from file subt_msgs/ultra_info.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_ULTRA_INFO_H
#define SUBT_MSGS_MESSAGE_ULTRA_INFO_H

#include <ros/service_traits.h>


#include <subt_msgs/ultra_infoRequest.h>
#include <subt_msgs/ultra_infoResponse.h>


namespace subt_msgs
{

struct ultra_info
{

typedef ultra_infoRequest Request;
typedef ultra_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ultra_info
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::ultra_info > {
  static const char* value()
  {
    return "839104ea8fff48a8d67dee52c3b6127a";
  }

  static const char* value(const ::subt_msgs::ultra_info&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::ultra_info > {
  static const char* value()
  {
    return "subt_msgs/ultra_info";
  }

  static const char* value(const ::subt_msgs::ultra_info&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::ultra_infoRequest> should match
// service_traits::MD5Sum< ::subt_msgs::ultra_info >
template<>
struct MD5Sum< ::subt_msgs::ultra_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::ultra_info >::value();
  }
  static const char* value(const ::subt_msgs::ultra_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::ultra_infoRequest> should match
// service_traits::DataType< ::subt_msgs::ultra_info >
template<>
struct DataType< ::subt_msgs::ultra_infoRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::ultra_info >::value();
  }
  static const char* value(const ::subt_msgs::ultra_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::ultra_infoResponse> should match
// service_traits::MD5Sum< ::subt_msgs::ultra_info >
template<>
struct MD5Sum< ::subt_msgs::ultra_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::ultra_info >::value();
  }
  static const char* value(const ::subt_msgs::ultra_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::ultra_infoResponse> should match
// service_traits::DataType< ::subt_msgs::ultra_info >
template<>
struct DataType< ::subt_msgs::ultra_infoResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::ultra_info >::value();
  }
  static const char* value(const ::subt_msgs::ultra_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_ULTRA_INFO_H
