// Generated by gencpp from file subt_msgs/artifactResponse.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_ARTIFACTRESPONSE_H
#define SUBT_MSGS_MESSAGE_ARTIFACTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <subt_msgs/ArtifactPoseArray.h>

namespace subt_msgs
{
template <class ContainerAllocator>
struct artifactResponse_
{
  typedef artifactResponse_<ContainerAllocator> Type;

  artifactResponse_()
    : artifacts()  {
    }
  artifactResponse_(const ContainerAllocator& _alloc)
    : artifacts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::subt_msgs::ArtifactPoseArray_<ContainerAllocator>  _artifacts_type;
  _artifacts_type artifacts;





  typedef boost::shared_ptr< ::subt_msgs::artifactResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::artifactResponse_<ContainerAllocator> const> ConstPtr;

}; // struct artifactResponse_

typedef ::subt_msgs::artifactResponse_<std::allocator<void> > artifactResponse;

typedef boost::shared_ptr< ::subt_msgs::artifactResponse > artifactResponsePtr;
typedef boost::shared_ptr< ::subt_msgs::artifactResponse const> artifactResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::artifactResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::artifactResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::artifactResponse_<ContainerAllocator1> & lhs, const ::subt_msgs::artifactResponse_<ContainerAllocator2> & rhs)
{
  return lhs.artifacts == rhs.artifacts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::artifactResponse_<ContainerAllocator1> & lhs, const ::subt_msgs::artifactResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::artifactResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::artifactResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::artifactResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::artifactResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::artifactResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::artifactResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::artifactResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69bcd85d6d5bff1b077f8d902e21fd09";
  }

  static const char* value(const ::subt_msgs::artifactResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69bcd85d6d5bff1bULL;
  static const uint64_t static_value2 = 0x077f8d902e21fd09ULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::artifactResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/artifactResponse";
  }

  static const char* value(const ::subt_msgs::artifactResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::artifactResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response data\n"
"ArtifactPoseArray artifacts\n"
"\n"
"\n"
"================================================================================\n"
"MSG: subt_msgs/ArtifactPoseArray\n"
"Header header\n"
"string camera\n"
"int32 count\n"
"ArtifactPose[] pose_array\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: subt_msgs/ArtifactPose\n"
"string Class\n"
"#string status				# O for non_return , X for return \n"
"int32 appear_count\n"
"float64 probability\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::subt_msgs::artifactResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::artifactResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.artifacts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct artifactResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::artifactResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::artifactResponse_<ContainerAllocator>& v)
  {
    s << indent << "artifacts: ";
    s << std::endl;
    Printer< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.artifacts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_ARTIFACTRESPONSE_H
