// Generated by gencpp from file subt_msgs/frame_switch.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_FRAME_SWITCH_H
#define SUBT_MSGS_MESSAGE_FRAME_SWITCH_H

#include <ros/service_traits.h>


#include <subt_msgs/frame_switchRequest.h>
#include <subt_msgs/frame_switchResponse.h>


namespace subt_msgs
{

struct frame_switch
{

typedef frame_switchRequest Request;
typedef frame_switchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct frame_switch
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::frame_switch > {
  static const char* value()
  {
    return "50cdb9fa30e06e199809b1d13df3e46b";
  }

  static const char* value(const ::subt_msgs::frame_switch&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::frame_switch > {
  static const char* value()
  {
    return "subt_msgs/frame_switch";
  }

  static const char* value(const ::subt_msgs::frame_switch&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::frame_switchRequest> should match
// service_traits::MD5Sum< ::subt_msgs::frame_switch >
template<>
struct MD5Sum< ::subt_msgs::frame_switchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::frame_switch >::value();
  }
  static const char* value(const ::subt_msgs::frame_switchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::frame_switchRequest> should match
// service_traits::DataType< ::subt_msgs::frame_switch >
template<>
struct DataType< ::subt_msgs::frame_switchRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::frame_switch >::value();
  }
  static const char* value(const ::subt_msgs::frame_switchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::frame_switchResponse> should match
// service_traits::MD5Sum< ::subt_msgs::frame_switch >
template<>
struct MD5Sum< ::subt_msgs::frame_switchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::frame_switch >::value();
  }
  static const char* value(const ::subt_msgs::frame_switchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::frame_switchResponse> should match
// service_traits::DataType< ::subt_msgs::frame_switch >
template<>
struct DataType< ::subt_msgs::frame_switchResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::frame_switch >::value();
  }
  static const char* value(const ::subt_msgs::frame_switchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_FRAME_SWITCH_H
