// Generated by gencpp from file subt_msgs/int32.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_INT32_H
#define SUBT_MSGS_MESSAGE_INT32_H

#include <ros/service_traits.h>


#include <subt_msgs/int32Request.h>
#include <subt_msgs/int32Response.h>


namespace subt_msgs
{

struct int32
{

typedef int32Request Request;
typedef int32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct int32
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::int32 > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::subt_msgs::int32&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::int32 > {
  static const char* value()
  {
    return "subt_msgs/int32";
  }

  static const char* value(const ::subt_msgs::int32&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::int32Request> should match
// service_traits::MD5Sum< ::subt_msgs::int32 >
template<>
struct MD5Sum< ::subt_msgs::int32Request>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::int32 >::value();
  }
  static const char* value(const ::subt_msgs::int32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::int32Request> should match
// service_traits::DataType< ::subt_msgs::int32 >
template<>
struct DataType< ::subt_msgs::int32Request>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::int32 >::value();
  }
  static const char* value(const ::subt_msgs::int32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::int32Response> should match
// service_traits::MD5Sum< ::subt_msgs::int32 >
template<>
struct MD5Sum< ::subt_msgs::int32Response>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::int32 >::value();
  }
  static const char* value(const ::subt_msgs::int32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::int32Response> should match
// service_traits::DataType< ::subt_msgs::int32 >
template<>
struct DataType< ::subt_msgs::int32Response>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::int32 >::value();
  }
  static const char* value(const ::subt_msgs::int32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_INT32_H
