// Generated by gencpp from file subt_msgs/int8Request.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_INT8REQUEST_H
#define SUBT_MSGS_MESSAGE_INT8REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_msgs
{
template <class ContainerAllocator>
struct int8Request_
{
  typedef int8Request_<ContainerAllocator> Type;

  int8Request_()
    : data(0)  {
    }
  int8Request_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::subt_msgs::int8Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::int8Request_<ContainerAllocator> const> ConstPtr;

}; // struct int8Request_

typedef ::subt_msgs::int8Request_<std::allocator<void> > int8Request;

typedef boost::shared_ptr< ::subt_msgs::int8Request > int8RequestPtr;
typedef boost::shared_ptr< ::subt_msgs::int8Request const> int8RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::int8Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::int8Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::int8Request_<ContainerAllocator1> & lhs, const ::subt_msgs::int8Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::int8Request_<ContainerAllocator1> & lhs, const ::subt_msgs::int8Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::int8Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::int8Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::int8Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::int8Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::int8Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::int8Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::int8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::subt_msgs::int8Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::int8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/int8Request";
  }

  static const char* value(const ::subt_msgs::int8Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::int8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request data\n"
"int8 data\n"
;
  }

  static const char* value(const ::subt_msgs::int8Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::int8Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct int8Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::int8Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::int8Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_INT8REQUEST_H
