// Generated by gencpp from file subt_msgs/SubTInfo.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_SUBTINFO_H
#define SUBT_MSGS_MESSAGE_SUBTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <subt_msgs/ArtifactPoseArray.h>

namespace subt_msgs
{
template <class ContainerAllocator>
struct SubTInfo_
{
  typedef SubTInfo_<ContainerAllocator> Type;

  SubTInfo_()
    : header()
    , robot_name()
    , robot_pose()
    , artifacts()  {
    }
  SubTInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , robot_pose(_alloc)
    , artifacts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robot_pose_type;
  _robot_pose_type robot_pose;

   typedef  ::subt_msgs::ArtifactPoseArray_<ContainerAllocator>  _artifacts_type;
  _artifacts_type artifacts;





  typedef boost::shared_ptr< ::subt_msgs::SubTInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::SubTInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SubTInfo_

typedef ::subt_msgs::SubTInfo_<std::allocator<void> > SubTInfo;

typedef boost::shared_ptr< ::subt_msgs::SubTInfo > SubTInfoPtr;
typedef boost::shared_ptr< ::subt_msgs::SubTInfo const> SubTInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::SubTInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::SubTInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::SubTInfo_<ContainerAllocator1> & lhs, const ::subt_msgs::SubTInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.robot_pose == rhs.robot_pose &&
    lhs.artifacts == rhs.artifacts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::SubTInfo_<ContainerAllocator1> & lhs, const ::subt_msgs::SubTInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::SubTInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::SubTInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::SubTInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::SubTInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::SubTInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::SubTInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::SubTInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e821f52944c112ea518ab90db2ed050a";
  }

  static const char* value(const ::subt_msgs::SubTInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe821f52944c112eaULL;
  static const uint64_t static_value2 = 0x518ab90db2ed050aULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::SubTInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/SubTInfo";
  }

  static const char* value(const ::subt_msgs::SubTInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::SubTInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string robot_name\n"
"geometry_msgs/Pose robot_pose\n"
"ArtifactPoseArray artifacts\n"
"#AnchorBallDetection anchorballs\n"
"#bool has_ball\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: subt_msgs/ArtifactPoseArray\n"
"Header header\n"
"string camera\n"
"int32 count\n"
"ArtifactPose[] pose_array\n"
"================================================================================\n"
"MSG: subt_msgs/ArtifactPose\n"
"string Class\n"
"#string status				# O for non_return , X for return \n"
"int32 appear_count\n"
"float64 probability\n"
"geometry_msgs/Pose pose\n"
;
  }

  static const char* value(const ::subt_msgs::SubTInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::SubTInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.robot_pose);
      stream.next(m.artifacts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubTInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::SubTInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::SubTInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
    s << indent << "robot_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_pose);
    s << indent << "artifacts: ";
    s << std::endl;
    Printer< ::subt_msgs::ArtifactPoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.artifacts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_SUBTINFO_H
