// Generated by gencpp from file pkg_why/img_srv.msg
// DO NOT EDIT!


#ifndef PKG_WHY_MESSAGE_IMG_SRV_H
#define PKG_WHY_MESSAGE_IMG_SRV_H

#include <ros/service_traits.h>


#include <pkg_why/img_srvRequest.h>
#include <pkg_why/img_srvResponse.h>


namespace pkg_why
{

struct img_srv
{

typedef img_srvRequest Request;
typedef img_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct img_srv
} // namespace pkg_why


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_why::img_srv > {
  static const char* value()
  {
    return "b8f81b07fa9e42ef3be27169c18c00a1";
  }

  static const char* value(const ::pkg_why::img_srv&) { return value(); }
};

template<>
struct DataType< ::pkg_why::img_srv > {
  static const char* value()
  {
    return "pkg_why/img_srv";
  }

  static const char* value(const ::pkg_why::img_srv&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_why::img_srvRequest> should match
// service_traits::MD5Sum< ::pkg_why::img_srv >
template<>
struct MD5Sum< ::pkg_why::img_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_why::img_srv >::value();
  }
  static const char* value(const ::pkg_why::img_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_why::img_srvRequest> should match
// service_traits::DataType< ::pkg_why::img_srv >
template<>
struct DataType< ::pkg_why::img_srvRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_why::img_srv >::value();
  }
  static const char* value(const ::pkg_why::img_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_why::img_srvResponse> should match
// service_traits::MD5Sum< ::pkg_why::img_srv >
template<>
struct MD5Sum< ::pkg_why::img_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_why::img_srv >::value();
  }
  static const char* value(const ::pkg_why::img_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_why::img_srvResponse> should match
// service_traits::DataType< ::pkg_why::img_srv >
template<>
struct DataType< ::pkg_why::img_srvResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_why::img_srv >::value();
  }
  static const char* value(const ::pkg_why::img_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_WHY_MESSAGE_IMG_SRV_H
